import Link from "next/link"

import { SiteHeader } from "@/components/site-header"
import { SiteFooter } from "@/components/site-footer"

export const metadata = {
  title: "Disclaimer — Not legal advice | Eviction Management",
  description:
    "Eviction Management is workflow software, not legal advice. User responsibility, jurisdictional limits, and warranties.",
}

export default function DisclaimerPage() {
  return (
    <>
      <SiteHeader />

      <main className="mx-auto max-w-3xl px-4 py-20 sm:px-6 lg:px-8">
        <Link href="/" className="text-sm text-slate-500 hover:text-slate-900">← Back home</Link>
        <h1 className="mt-6 text-4xl font-semibold tracking-tight text-slate-900">
          Disclaimer — not legal advice
        </h1>
        <p className="mt-6 rounded-md border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">
          <strong>Read this before using Eviction Management.</strong> The Service is workflow
          software. It is not a substitute for advice from counsel admitted in your jurisdiction.
        </p>

        <Section title="No attorney-client relationship">
          Use of Eviction Management (&quot;the Service&quot;) does not create an attorney-client
          relationship between you and Homeowner Hub, its affiliates, contributors, or the
          attorneys who reviewed any jurisdictional playbook.
        </Section>

        <Section title="Software, not advice">
          Computed deadlines, generated documents, and playbook content are tools. Statutes
          change, local rules change, individual judges issue standing orders, and case-specific
          facts can move any deadline. <strong>You are responsible for confirming every deadline,
          every form, and every filing against the law currently in effect in your jurisdiction
          before relying on it.</strong>
        </Section>

        <Section title="User responsibility">
          You are responsible for: (a) the accuracy of facts entered into the Service; (b)
          compliance with all applicable federal, state, and local laws including the Fair
          Housing Act, the CARES Act where applicable, and any state and local notice or
          moratorium requirements; (c) the proper service, filing, and execution of any
          document generated by the Service; and (d) the conduct of any hearing or proceeding.
        </Section>

        <Section title="Jurisdictional limits">
          A playbook is current as of its published version date. Coverage of a jurisdiction
          does not warrant fitness for any particular case. Where a jurisdiction is not listed
          as live, the Service provides no jurisdiction-specific computation.
        </Section>

        <Section title="No warranty of outcome">
          Nothing in the Service, marketing materials, or communications guarantees any case
          outcome, possession, judgment, or collection.
        </Section>

        <Section title="Contact">
          Questions about this disclaimer:{" "}
          <a className="text-rose-700 underline-offset-2 hover:underline" href="mailto:legal@eviction.homeowner-hub.app">
            legal@eviction.homeowner-hub.app
          </a>
          .
        </Section>
      </main>

      <SiteFooter />
    </>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-10">
      <h2 className="text-xl font-semibold tracking-tight text-slate-900">{title}</h2>
      <div className="mt-3 text-base leading-relaxed text-slate-700">{children}</div>
    </section>
  )
}
